import = ["/Users/axelav/.config/alacritty/tokyo-night.toml"]
live_config_reload = true
working_directory = "None"

[font]
size = 13.0

[font.bold]
family = "SF Mono"
style = "Medium"

[font.bold_italic]
family = "SF Mono"
style = "Medium Italic"

[font.italic]
family = "SF Mono"
style = "Regular Italic"

[font.normal]
family = "SF Mono"
style = "Regular"

[scrolling]
history = 100000
multiplier = 3

[shell]
args = ["--login", "-c", "tmux new-session -A -s main"]
program = "/bin/zsh"

[window]
decorations = "buttonless"
dynamic_padding = true
dynamic_title = true
opacity = 0.95
startup_mode = "Maximized"

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 16
y = 16
