[general]
live_config_reload = true
working_directory = "None"
import = ["/Users/axelav/.config/alacritty/tokyo-night.toml"]

[font]
size = 13.0

[font.bold]
family = "BlexMono Nerd Font"
style = "Medium"

[font.bold_italic]
family = "BlexMono Nerd Font"
style = "Medium Italic"

[font.italic]
family = "BlexMono Nerd Font"
style = "Italic"

[font.normal]
family = "BlexMono Nerd Font"
style = "Regular"

[scrolling]
history = 100000
multiplier = 3

[terminal.shell]
args = ["--login", "-c", "tmux new-session -A -s main"]
program = "/bin/zsh"

[window]
decorations = "buttonless"
dynamic_padding = true
dynamic_title = true
opacity = 0.95
startup_mode = "Maximized"
option_as_alt = "OnlyLeft"

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 8
y = 8
