#!/usr/bin/env zsh

# homebrew
which -s brew
if [[ $? != 0 ]] ; then
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  # TODO run these two lines to make `brew` available in path
  # echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> /Users/axelav/.profile
  # eval "$(/opt/homebrew/bin/brew shellenv)"
else
  brew update
  brew upgrade
fi

# TODO
# brew bundle install --file ./Brewfile

# gnu core utils & `find`, `locate`, `updatedb`, `xargs`
brew install coreutils
brew install findutils

# os x tools
# brew tap homebrew/dupes
# brew install homebrew/dupes/grep

# chest
# brew install lukechilds/tap/chest

# everything else
brew install \
  emacs \
  ffmpeg \
  fd \
  fzf \
  gh \
  git \
  gnu-sed \
  gnupg \
  htop \
  httpie \
  imagemagick \
  jq \
  lame \
  lsd \
  mutt \
  neovim \
  nmap \
  pass \
  reattach-to-user-namespace \
  ripgrep \
  stow \
  tig \
  tmux \
  vim \
  # youtube-dl \
  yt-dlp \
  z

# casks
brew install \
  # actual \
  affinity-photo \
  # NOTE free version not available on brew, use:
  # https://apps.apple.com/us/app/adguard-for-safari/id1440147259?mt=12
  # adguard \
  alacritty \
  brave-browser \
  calibre \
  firefox \
  google-chrome \
  google-earth-pro \
  istat-menus \
  iterm2 \
  macvim \
  rectangle \
  soulseek \
  time-out \
  tor-browser

# remove outdated versions
brew cleanup
