#!/usr/bin/env zsh

# homebrew
which -s brew
if [[ $? != 0 ]] ; then
  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
else
  brew update
  brew upgrade
fi

# gnu core utils & `find`, `locate`, `updatedb`, `xargs`
brew install coreutils
brew install findutils

# os x tools
# brew tap homebrew/dupes
# brew install homebrew/dupes/grep

# chest
# brew install lukechilds/tap/chest

# everything else
brew install \
  emacs \
  ffmpeg \
  fd \
  fzf \
  github/gh/gh \
  git \
  gnu-sed \
  gnupg \
  htop \
  httpie \
  imagemagick \
  jq \
  lame \
  mutt \
  neovim \
  nmap \
  pass \
  reattach-to-user-namespace \
  ripgrep \
  stow \
  tmux \
  vim \
  youtube-dl \
  z \
  zsh

# remove outdated versions
brew cleanup
