#!/usr/bin/env zsh

brew cask install \
  alacritty \
  beaker-browser \
  caffeine \
  firefox \
  google-chrome \
  google-earth-pro \
  imageoptim \
  istat-menus \
  iterm2 \
  macvim \
  tor-browser \
  transmission \
  visual-studio-code \
  vlc
